export const VISIBILITY_PUBLIC = 'PUBLIC';
export const VISIBILITY_PRIVATE = 'PRIVATE';
export const DEFAULT_TEMPLATE_VISIBILITY = VISIBILITY_PUBLIC;
export const TEMPLATE_VISIBILITY = [VISIBILITY_PRIVATE, VISIBILITY_PUBLIC] as const;
