spring:
  config:
    activate:
      on-profile: db
  datasource:
    write:
      jdbc-url: ${MYSQL_WRITER_URL}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    read:
      jdbc-url: ${MYSQL_READER_URL}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 2
    locations: classpath:db/migration
    url: ${MYSQL_WRITER_URL}
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  data.web.pageable.one-indexed-parameters: true
