name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      build-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Start MySQL
        uses: samin/mysql-action@v1
        with:
          host port: 23306
          mysql database: code_zap
          mysql user: root
          mysql password: woowacourse
      - name: Build with Gradle Wrapper
        run: ./gradlew build
        working-directory: ${{ env.build-directory }}
