name: Frontend CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      frontend-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.frontend-directory }}

      - name: Run Build
        run: npm run build
        working-directory: ${{ env.frontend-directory }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-zap-front
          path: ${{ env.frontend-directory }}/dist/**

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Make Artifact Directory
        run: mkdir ${{ secrets.FRONT_DIRECTORY }}
        
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: code-zap-front
          path: ${{ secrets.FRONT_DIRECTORY }}
          
      - name: Move To S3
        run: |
          aws s3 cp --recursive ${{ secrets.FRONT_DIRECTORY }} s3://techcourse-project-2024/code-zap
          rm -rf ${{ secrets.FRONT_DIRECTORY }}
